###
GET http://127.0.0.1:3000/orders/WBTC HTTP/1.1

###
GET http://127.0.0.1:3000/orderBook/WBTC?depth=2 HTTP/1.1

###
GET http://127.0.0.1:3000/rates HTTP/1.1

###
GET http://127.0.0.1:3000/margin/cZifcgcutJWjcCnLheB1Zv3LMkB1jLkiREWdE5hYyGZNx97uF HTTP/1.1

###
GET http://127.0.0.1:3000/lockedBalance/cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X HTTP/1.1

###
GET http://127.0.0.1:3000/orders/ETH/cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X HTTP/1.1

###
GET http://127.0.0.1:3000/bestPrices/WBTC HTTP/1.1

###
GET http://127.0.0.1:3000/bestPrices/BNB HTTP/1.1


###
GET http://127.0.0.1:3000/trades/WBTC HTTP/1.1

###
GET http://127.0.0.1:3000/trades/WBTC?page=0&pageSize=5 HTTP/1.1

###
GET http://127.0.0.1:3000/tradesByAddress/WBTC/cZhTPXeT5o3DVgEnRQ95Vi8BNiyPsDoFDovXZLCeWmDKB89WW HTTP/1.1

###
GET http://127.0.0.1:3000/tradesByAddress/WBTC/cZhTPXeT5o3DVgEnRQ95Vi8BNiyPsDoFDovXZLCeWmDKB89WW?page=0&pageSize=3 HTTP/1.1

###
GET http://127.0.0.1:3000/balances/WBTC/cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X HTTP/1.1

###
POST http://127.0.0.1:3000/sudo/deposit HTTP/1.1
content-type: application/json

{
  "address": "cZgMUDuyxuKYbpy39TpGcUVkVdaEPvSJtWySPKuGHnz6Ge57N",
  "to": "cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X",
  "token": "GENS",
  "amount": 1000000
}

###
POST http://127.0.0.1:3000/deposit HTTP/1.1
content-type: application/json

{
  "address": "cZifcgcutJWjcCnLheB1Zv3LMkB1jLkiREWdE5hYyGZNx97uF",
  "token": "WBTC",
  "amount": 900
}

###
POST http://127.0.0.1:3000/withdraw HTTP/1.1
content-type: application/json

{
  "address": "cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X",
  "token": "WBTC",
  "amount": 0.01
}

###
POST http://127.0.0.1:3000/marketOrder HTTP/1.1
content-type: application/json

{
  "address": "cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X",
  "token": "WBTC",
  "amount": 0.1,
  "direction": "Buy"
}

###
GET http://127.0.0.1:3000/marketOrder/16448489453521 HTTP/1.1

###
POST http://127.0.0.1:3000/limitOrder HTTP/1.1
content-type: application/json

{
  "address": "cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X",
  "token": "GENS",
  "limitPrice": 0.029,
  "amount": 1000,
  "direction": "Sell"
}

###
PUT http://127.0.0.1:3000/limitOrder HTTP/1.1
content-type: application/json

{
  "address": "cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X",
  "token": "WBTC",
  "limitPrice": 39002,
  "limitPriceNew": 39003,
  "amountNew": 0.1,
  "direction": "Buy",
  "messageId": "16454558118451",
  "nonce": 71,
  "tip": 10
}

###
GET http://127.0.0.1:3000/limitOrder/1645778926226200 HTTP/1.1

###
DELETE http://127.0.0.1:3000/limitOrder HTTP/1.1
content-type: application/json

{
  "address": "cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X",
  "token": "WBTC",
  "price": 34940,
  "orderId": 1620
}


###
GET http://127.0.0.1:3000/pendingExtrinsics/cZifcgcutJWjcCnLheB1Zv3LMkB1jLkiREWdE5hYyGZNx97uF