###
GET http://127.0.0.1:3000/chainId HTTP/1.1

###
GET http://127.0.0.1:3000/orderBook/BNB?depth=20 HTTP/1.1

###
GET http://127.0.0.1:3000/rates HTTP/1.1

###
GET http://127.0.0.1:3000/token/DOT HTTP/1.1

###
GET http://127.0.0.1:3000/margin/cZifcgcutJWjcCnLheB1Zv3LMkB1jLkiREWdE5hYyGZNx97uF HTTP/1.1

###
GET http://127.0.0.1:3000/lockedBalance/cg7ENkxLYjpXV2QWjw5murokf8ZxUNkjjhCkqqxxAP7svN49A HTTP/1.1

###
GET http://127.0.0.1:3000/orders/BNB/cg7ENkxLYjpXV2QWjw5murokf8ZxUNkjjhCkqqxxAP7svN49A HTTP/1.1

###
GET http://127.0.0.1:3000/bestPrices/WBTC HTTP/1.1

###
GET http://127.0.0.1:3000/bestPrices/EQ HTTP/1.1
###
GET http://127.0.0.1:3000/orders/EQ HTTP/1.1

###
GET http://127.0.0.1:3000/orderBook/EQ?depth=2 HTTP/1.1

###
GET http://127.0.0.1:3000/rates HTTP/1.1

###
GET http://127.0.0.1:3000/token/KSM HTTP/1.1

###
GET http://127.0.0.1:3000/margin/cZifcgcutJWjcCnLheB1Zv3LMkB1jLkiREWdE5hYyGZNx97uF HTTP/1.1

###
GET http://127.0.0.1:3000/lockedBalance/cZja3kBcPmQiMZAsPKXeVzrrz78FYA2NftKU1bDZLcPhckq8e HTTP/1.1

###
GET http://127.0.0.1:3000/orders/KSM/cZja3kBcPmQiMZAsPKXeVzrrz78FYA2NftKU1bDZLcPhckq8e HTTP/1.1

###
GET http://127.0.0.1:3000/bestPrices/WBTC HTTP/1.1

###
GET http://127.0.0.1:3000/bestPrices/BNB HTTP/1.1


###
GET http://127.0.0.1:3000/trades/ETH HTTP/1.1

###
GET http://127.0.0.1:3000/trades/WBTC?page=0&pageSize=5 HTTP/1.1

###
GET http://127.0.0.1:3000/tradesByAddress/WBTC/cZhTPXeT5o3DVgEnRQ95Vi8BNiyPsDoFDovXZLCeWmDKB89WW HTTP/1.1

###
GET http://127.0.0.1:3000/tradesByAddress/WBTC/cZhTPXeT5o3DVgEnRQ95Vi8BNiyPsDoFDovXZLCeWmDKB89WW?page=0&pageSize=3 HTTP/1.1

###
GET http://127.0.0.1:3000/balances/BNB/cg7ENkxLYjpXV2QWjw5murokf8ZxUNkjjhCkqqxxAP7svN49A HTTP/1.1

###
GET http://127.0.0.1:3000/balancesMm/EQD HTTP/1.1

###
GET http://127.0.0.1:3000/mmPool/KSM HTTP/1.1

###
GET http://127.0.0.1:3000/marketMaker/1/KSM HTTP/1.1

###
GET http://127.0.0.1:3000/traderAddress/cg7ENkxLYjpXV2QWjw5murokf8ZxUNkjjhCkqqxxAP7svN49A HTTP/1.1

###
GET http://127.0.0.1:3000/balancesMm/KSM/cZfMdXut7KkaRNnBSAAnzwehVwH7gZuLNNMT9D9Xv3bcqMSpQ HTTP/1.1

###
POST http://127.0.0.1:3000/sudo/deposit HTTP/1.1
content-type: application/json

{
  "address": "cZgMUDuyxuKYbpy39TpGcUVkVdaEPvSJtWySPKuGHnz6Ge57N",
  "to": "cZkU6MjtFA6FXxpJnnLq337DNPnLp74xrGen5trac4JQvEUcq",
  "token": "KSM",
  "amount": 1000000
}

###
POST http://127.0.0.1:3000/deposit HTTP/1.1
content-type: application/json

{
  "address": "cg7ENkxLYjpXV2QWjw5murokf8ZxUNkjjhCkqqxxAP7svN49A",
  "token": "BNB",
  "amount": 77,
  "isUsingPool": false
}

###
POST http://127.0.0.1:3000/withdraw HTTP/1.1
content-type: application/json

{
  "address": "cg7ENkxLYjpXV2QWjw5murokf8ZxUNkjjhCkqqxxAP7svN49A",
  "token": "BNB",
  "amount": 77,
  "isUsingPool": false
}

###
POST http://127.0.0.1:3000/withdraw HTTP/1.1
content-type: application/json

{
  "address": "cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X",
  "token": "ETH",
  "amount": 11
}

###
POST http://127.0.0.1:3000/withdraw HTTP/1.1
content-type: application/json

{
  "address": "cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X",
  "token": "ETH",
  "amount": 11,
  "isUsingPool": true
}

###
POST http://127.0.0.1:3000/marketOrder HTTP/1.1
content-type: application/json

{
  "address": "cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X",
  "token": "WBTC",
  "amount": 0.1,
  "direction": "Buy"
}

###
GET http://127.0.0.1:3000/marketOrder/16612561114441 HTTP/1.1

###
POST http://127.0.0.1:3000/limitOrder HTTP/1.1
content-type: application/json

{
  "address": "cg7ENkxLYjpXV2QWjw5murokf8ZxUNkjjhCkqqxxAP7svN49A",
  "token": "BNB",
  "limitPrice": 300,
  "amount": 1,
  "direction": "sell",
  "isUsingPool": false
}

###
POST http://127.0.0.1:3000/limitOrder HTTP/1.1
content-type: application/json

{
  "address": "cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X",
  "token": "WBTC",
  "limitPrice": 43250,
  "amount": 0.7,
  "direction": "sell",
  "isUsingPool": true
}

###
PUT http://127.0.0.1:3000/limitOrder HTTP/1.1
content-type: application/json

{
  "address": "cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X",
  "token": "WBTC",
  "limitPrice": 39002,
  "limitPriceNew": 39003,
  "amountNew": 0.1,
  "direction": "sell",
  "messageId": "16454558118451",
  "nonce": 71,
  "tip": 10
}

###
PUT http://127.0.0.1:3000/limitOrder HTTP/1.1
content-type: application/json

{
  "address": "cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X",
  "token": "ETH",
  "limitPrice": 3101,
  "limitPriceNew": 3091,
  "amountNew": 7,
  "direction": "sell",
  "messageId": "16497657461334",
  "nonce": 51,
  "tip": 10,
  "isUsingPool": true
}

###
GET http://127.0.0.1:3000/limitOrder/16623662886741 HTTP/1.1

###
DELETE http://127.0.0.1:3000/limitOrder HTTP/1.1
content-type: application/json

{
  "address": "cg7ENkxLYjpXV2QWjw5murokf8ZxUNkjjhCkqqxxAP7svN49A",
  "token": "EQ",
  "price": 1,
  "orderId": 1
}

###
DELETE http://127.0.0.1:3000/limitOrders HTTP/1.1
content-type: application/json

{
  "address": "cg7ENkxLYjpXV2QWjw5murokf8ZxUNkjjhCkqqxxAP7svN49A",
  "isUsingPool": false,
  "orders": [
    {
      "token": "BNB",
      "price": 265,
      "orderId": 176
    },
    {
      "token": "BNB",
      "price": 300,
      "orderId": 177
    }
  ]
}

###
GET http://127.0.0.1:3000/orders/WBTC/cZifcgcutJWjcCnLheB1Zv3LMkB1jLkiREWdE5hYyGZNx97uF HTTP/1.1


###
DELETE http://127.0.0.1:3000/limitOrder HTTP/1.1
content-type: application/json

{
  "address": "cZirADTgk9CYy2ed3y1UPh8jTmWoes2SRd1JSUDntkPpiMQ6X",
  "token": "KSM",
  "price": 182,
  "orderId": 40258,
  "isUsingPool": true
}


###
GET http://127.0.0.1:3000/pendingExtrinsics/cZifcgcutJWjcCnLheB1Zv3LMkB1jLkiREWdE5hYyGZNx97uF

###
GET http://127.0.0.1:3000/balances/BNB/cg7ENkxLYjpXV2QWjw5murokf8ZxUNkjjhCkqqxxAP7svN49A HTTP/1.1

###
POST http://127.0.0.1:3000/limitOrder HTTP/1.1
content-type: application/json

{
  "address": "cg7ENkxLYjpXV2QWjw5murokf8ZxUNkjjhCkqqxxAP7svN49A",
  "token": "BNB",
  "limitPrice": 300,
  "amount": 1,
  "direction": "sell",
  "isUsingPool": false
}

###
GET http://127.0.0.1:3000/orders/BNB/cg7ENkxLYjpXV2QWjw5murokf8ZxUNkjjhCkqqxxAP7svN49A HTTP/1.1